[project]
version = "0.0.0"

[tool.commitizen]
version = "1.1.0"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
version_files = [
    "pyproject.toml:version",
]