name: gfc_wrapper_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sepal-ui>=2.22.1,<3
  - pygaul<0.4  # pin to avoid GAUL 2024 property name mismatch with sepal_ui
  - pyproj  # Always include to avoid PROJ conflicts
  - gdal=3.8.3
  - bqplot
  - matplotlib
  - numpy
  - pandas
  - rasterio<=1.4.3
  - pip
  - pip:
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
